# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest



steps:
    - task: CmdLine@2
      continueOnError: true
      inputs:
      
        script: |
          ls -ltr
          pwd
          docker run -v /home/vsts/work/1/s/collections:/etc/postman -t gunesmes/newman-postman-html-report run /etc/postman/petstore.json -r htmlextra --reporter-htmlextra-title "My Newman Report"
          ls -ltr collections
       
    - task: UploadPostmanHtmlReport@1
      displayName: 'Upload Postman Html Report'
      inputs:
        cwd: '$(System.DefaultWorkingDirectory)'
        tabName: 'Postman Test'


   


