# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest



steps:
    - task: CmdLine@2
      continueOnError: true
      inputs:
      
        script: |
          mkdir testing
          cp Pet.postman_collection.json testing/
          docker run -v ~/testing:/etc/newman -t postman/newman run ./Pet.postman_collection.json  --reporters cli,junit --reporter-junit-export junit-report.xml
            
          sleep 40
    - task: PublishTestResults@2
      displayName: 'Publish Test Results for postman'
      inputs:
       testResultsFormat: 'JUnit'
       searchFolder: '$(System.DefaultWorkingDirectory)'
       testResultsFiles: '**/*.xml'       
       mergeTestResults: true
       failTaskOnFailedTests: false

  

