# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest



steps:
    - task: CmdLine@2
      continueOnError: true
      inputs:
      
        script: |
          ls -ltr
          pwd
          docker run -v /home/vsts/work/1/s/collections:/etc/postman -t dannydainton/htmlextra run /etc/postman/petstore.json --reporters=cli,json,junit,htmlextra --reporter-junit-export /etc/postman/junitreport.xml --reporter-htmlextra-export /etc/postman/postmanreport.html 
          
          ls -ltr collections        
          
          pwd
          ls -ltr $(Pipeline.Workspace)
          ls -ltr /home/vsts/work/_tasks
       
    - task: PublishTestResults@2
      displayName: 'Publish Test Results for postman'
      inputs:
       testResultsFormat: 'JUnit'
       searchFolder: '$(System.DefaultWorkingDirectory)'
       testResultsFiles: '**/*.xml'       
       mergeTestResults: true
       failTaskOnFailedTests: false 
           
    - task: UploadPostmanHtmlReport@1
      inputs:
        cwd: '**/*'