# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest



steps:
    - task: CmdLine@2
      continueOnError: true
      inputs:
      
        script: |
          ls -ltr
          pwd
          docker run -v /home/vsts/work/1/s/collections:/etc/postman -t postman/newman run /etc/postman/petstore.json  --reporters cli,junit --reporter-junit-export /etc/postman/junit-report.xml
          ls -ltr collections
          sleep 40
    - task: PublishTestResults@2
      displayName: 'Publish Test Results for postman'
      inputs:
       testResultsFormat: 'JUnit'
       searchFolder: '$(System.DefaultWorkingDirectory)'
       testResultsFiles: '**/*.xml'       
       mergeTestResults: true
       failTaskOnFailedTests: false
    - task: publishhtmlreport@1
      inputs:
        htmlType: 'Jmeter'
        JmeterReportsPath: '$(Pipeline.Workspace)/s/etc/postman'
  

